--- #YAML:1.0
name:                Bundle-W3C-Validator
version:             0.8.5
abstract:            Bundle of modules required by the W3C Markup Validator
license:             open_source
author:              
    - W3C QA-dev Team <public-qa-dev@w3.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           2.81
    CGI::Carp:                     0
    Config::General:               2.32
    Encode:                        0
    Encode::Alias:                 0
    Encode::HanExtra:              0
    Encode::JIS2K:                 0
    File::Spec::Functions:         0
    HTML::Encoding:                0.52
    HTML::Parser:                  3.24
    HTML::Template:                2.6
    HTML::Tidy:                    0
    HTTP::Headers::Auth:           0
    HTTP::Headers::Util:           0
    HTTP::Message:                 1.52
    HTTP::Negotiate:               0
    HTTP::Request:                 0
    JSON:                          2
    LWP::UserAgent:                2.032
    Net::hostent:                  0
    Net::IP:                       0
    SGML::Parser::OpenSP:          0.991
    Socket:                        0
    String::Approx:                0
    URI:                           0
    URI::Escape:                   0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
