--- #YAML:1.0
name:                Bundle-W3C-Validator
version:             0.8.4
abstract:            Bundle of modules required by the W3C Markup Validator
license:             ~
author:              
    - The W3C Markup Validator Team <www-validator@w3.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           2.81
    Config::General:               2.31
    Encode:                        0
    Encode::HanExtra:              0
    Encode::JIS2K:                 0
    File::Spec::Functions:         0
    HTML::Encoding:                0.52
    HTML::Parser:                  3.24
    HTML::Template:                2.6
    LWP::UserAgent:                2.032
    Net::IP:                       0
    SGML::Parser::OpenSP:          0
    URI:                           0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
